### PR TITLE
Setup ruff linter

### PR DESCRIPTION
**Pull request by Maneren**
Adds a configuration for [ruff](https://github.com/astral-sh/ruff) linter. It checks code quality and catches common mistakes and typos.

It is a low priority now, but nice to have.

Possible to add it to the CI for bonus points.

### CODE REVIEW

**Review by vokymir — APPROVED** [review]
Important imo, should add to CI asap.

**Comment by Maneren** [comment]
okok, will do it in this branch then xD

**Comment by Maneren** [comment]
We have to fix all of the existing issues first tho (around 100, mostly docs and typing), otherwise no future PR will be accepted

**Review by Minsqui — APPROVED** [review]
Lovely

**Comment by Maneren** [comment]
Super

**Pull request merged**
